const Numbers = {
  '00': { Enum: 37, Title: '00', Payout: 35 },
  '0': { Enum: 0, Title: '0', Payout: 35 },
  '1': { Enum: 1, Title: '1', Payout: 35 },
  '2': { Enum: 2, Title: '2', Payout: 35 },
  '3': { Enum: 3, Title: '3', Payout: 35 },
  '4': { Enum: 4, Title: '4', Payout: 35 },
  '5': { Enum: 5, Title: '5', Payout: 35 },
  '6': { Enum: 6, Title: '6', Payout: 35 },
  '7': { Enum: 7, Title: '7', Payout: 35 },
  '8': { Enum: 8, Title: '8', Payout: 35 },
  '9': { Enum: 9, Title: '9', Payout: 35 },
  '10': { Enum: 10, Title: '10', Payout: 35 },
  '11': { Enum: 11, Title: '11', Payout: 35 },
  '12': { Enum: 12, Title: '12', Payout: 35 },
  '13': { Enum: 13, Title: '13', Payout: 35 },
  '14': { Enum: 14, Title: '14', Payout: 35 },
  '15': { Enum: 15, Title: '15', Payout: 35 },
  '16': { Enum: 16, Title: '16', Payout: 35 },
  '17': { Enum: 17, Title: '17', Payout: 35 },
  '18': { Enum: 18, Title: '18', Payout: 35 },
  '19': { Enum: 19, Title: '19', Payout: 35 },
  '20': { Enum: 20, Title: '20', Payout: 35 },
  '21': { Enum: 21, Title: '21', Payout: 35 },
  '22': { Enum: 22, Title: '22', Payout: 35 },
  '23': { Enum: 23, Title: '23', Payout: 35 },
  '24': { Enum: 24, Title: '24', Payout: 35 },
  '25': { Enum: 25, Title: '25', Payout: 35 },
  '26': { Enum: 26, Title: '26', Payout: 35 },
  '27': { Enum: 27, Title: '27', Payout: 35 },
  '28': { Enum: 28, Title: '28', Payout: 35 },
  '29': { Enum: 29, Title: '29', Payout: 35 },
  '30': { Enum: 30, Title: '30', Payout: 35 },
  '31': { Enum: 31, Title: '31', Payout: 35 },
  '32': { Enum: 32, Title: '32', Payout: 35 },
  '33': { Enum: 33, Title: '33', Payout: 35 },
  '34': { Enum: 34, Title: '34', Payout: 35 },
  '35': { Enum: 35, Title: '35', Payout: 35 },
  '36': { Enum: 36, Title: '36', Payout: 35 },
};

const Colors = {
  Red: {
    Title: 'Red',
    Enum: 38,
    Bettable: true,
    Payout: 1,
    Includes: [
      Numbers['1'],
      Numbers['3'],
      Numbers['5'],
      Numbers['7'],
      Numbers['9'],
      Numbers['12'],
      Numbers['14'],
      Numbers['16'],
      Numbers['18'],
      Numbers['19'],
      Numbers['21'],
      Numbers['23'],
      Numbers['25'],
      Numbers['27'],
      Numbers['30'],
      Numbers['32'],
      Numbers['34'],
      Numbers['36'],
    ],
  },
  Black: {
    Title: 'Black',
    Enum: 39,
    Bettable: true,
    Payout: 1,
    Includes: [
      Numbers['2'],
      Numbers['4'],
      Numbers['6'],
      Numbers['8'],
      Numbers['10'],
      Numbers['11'],
      Numbers['13'],
      Numbers['15'],
      Numbers['17'],
      Numbers['20'],
      Numbers['22'],
      Numbers['24'],
      Numbers['26'],
      Numbers['28'],
      Numbers['29'],
      Numbers['31'],
      Numbers['33'],
      Numbers['35'],
    ],
  },
  Green: {
    Bettable: false,
    Includes: [Numbers['00'], Numbers['0']],
  },
};

const Aggregates = {
  '1st 12': {
    Title: '1st 12',
    Enum: 40,
    Payout: 2,
    Includes: [
      Numbers['1'],
      Numbers['2'],
      Numbers['3'],
      Numbers['4'],
      Numbers['5'],
      Numbers['6'],
      Numbers['7'],
      Numbers['8'],
      Numbers['9'],
      Numbers['10'],
      Numbers['11'],
      Numbers['12'],
    ],
  },
  '2nd 12': {
    Title: '2nd 12',
    Enum: 41,
    Payout: 2,
    Includes: [
      Numbers['13'],
      Numbers['14'],
      Numbers['15'],
      Numbers['16'],
      Numbers['17'],
      Numbers['18'],
      Numbers['19'],
      Numbers['20'],
      Numbers['21'],
      Numbers['22'],
      Numbers['23'],
      Numbers['24'],
    ],
  },
  '3rd 12': {
    Title: '3rd 12',
    Enum: 42,
    Payout: 2,
    Includes: [
      Numbers['25'],
      Numbers['26'],
      Numbers['27'],
      Numbers['28'],
      Numbers['29'],
      Numbers['30'],
      Numbers['31'],
      Numbers['32'],
      Numbers['33'],
      Numbers['34'],
      Numbers['35'],
      Numbers['36'],
    ],
  },
  '1 to 18': {
    Title: '1 to 18',
    Enum: 43,
    Payout: 1,
    Includes: [
      Numbers['1'],
      Numbers['2'],
      Numbers['3'],
      Numbers['4'],
      Numbers['5'],
      Numbers['6'],
      Numbers['7'],
      Numbers['8'],
      Numbers['9'],
      Numbers['10'],
      Numbers['11'],
      Numbers['12'],
      Numbers['13'],
      Numbers['14'],
      Numbers['15'],
      Numbers['16'],
      Numbers['17'],
      Numbers['18'],
    ],
  },
  '19 to 36': {
    Title: '19 to 36',
    Enum: 44,
    Payout: 1,
    Includes: [
      Numbers['19'],
      Numbers['20'],
      Numbers['21'],
      Numbers['22'],
      Numbers['23'],
      Numbers['24'],
      Numbers['25'],
      Numbers['26'],
      Numbers['27'],
      Numbers['28'],
      Numbers['29'],
      Numbers['30'],
      Numbers['31'],
      Numbers['32'],
      Numbers['33'],
      Numbers['34'],
      Numbers['35'],
      Numbers['36'],
    ],
  },
  '1st Col': {
    Title: '1st Col',
    Enum: 45,
    Payout: 2,
    Includes: [
      Numbers['1'],
      Numbers['4'],
      Numbers['7'],
      Numbers['10'],
      Numbers['13'],
      Numbers['16'],
      Numbers['19'],
      Numbers['22'],
      Numbers['25'],
      Numbers['28'],
      Numbers['31'],
      Numbers['34'],
    ],
  },
  '2nd Col': {
    Title: '2nd Col',
    Enum: 46,
    Payout: 2,
    Includes: [
      Numbers['2'],
      Numbers['5'],
      Numbers['8'],
      Numbers['11'],
      Numbers['14'],
      Numbers['17'],
      Numbers['20'],
      Numbers['23'],
      Numbers['26'],
      Numbers['29'],
      Numbers['32'],
      Numbers['35'],
    ],
  },
  '3rd Col': {
    Title: '3rd Col',
    Enum: 47,
    Payout: 2,
    Includes: [
      Numbers['3'],
      Numbers['6'],
      Numbers['9'],
      Numbers['12'],
      Numbers['15'],
      Numbers['18'],
      Numbers['21'],
      Numbers['24'],
      Numbers['27'],
      Numbers['30'],
      Numbers['33'],
      Numbers['36'],
    ],
  },
  Odd: {
    Title: 'Odd',
    Enum: 48,
    Payout: 1,
    Includes: [
      Numbers['1'],
      Numbers['3'],
      Numbers['5'],
      Numbers['7'],
      Numbers['9'],
      Numbers['11'],
      Numbers['13'],
      Numbers['15'],
      Numbers['17'],
      Numbers['19'],
      Numbers['21'],
      Numbers['23'],
      Numbers['25'],
      Numbers['27'],
      Numbers['29'],
      Numbers['31'],
      Numbers['33'],
      Numbers['35'],
    ],
  },
  Even: {
    Title: 'Even',
    Enum: 49,
    Payout: 1,
    Includes: [
      Numbers['2'],
      Numbers['4'],
      Numbers['6'],
      Numbers['8'],
      Numbers['10'],
      Numbers['12'],
      Numbers['14'],
      Numbers['16'],
      Numbers['18'],
      Numbers['20'],
      Numbers['22'],
      Numbers['24'],
      Numbers['26'],
      Numbers['28'],
      Numbers['30'],
      Numbers['32'],
      Numbers['34'],
      Numbers['36'],
    ],
  },
  Red: Colors.Red,
  Black: Colors.Black,
};

const Bets = {
  Numbers,
  Colors,
  Aggregates,
};

export default Bets;
